### ISSUE TITLE
C# support?

### ISSUE THREAD

**Issue by sollidsnake** [emacs-lsp/lsp-sonarlint#18]
Are there plans to add C# support to this package?

**Comment by necto** [comment]
This package is based on the SonarLint language server from [SonarLint for VSCode](https://www.sonarsource.com/products/sonarlint/features/vs-code/). As you can see, SonarLint for VSCode does not support C#, hence its language server also provides no support for C# analysis.
In order to enable lsp-sonarlint to work with C# code, it first has to be supported in SonarLint for VSCode.
As you can see in the [SonarLint roadmap](https://www.sonarsource.com/products/sonarlint/roadmap/), it is not planned for the near future.

Feel free to suggest this feature using the "+ Submit idea" button in [the SonarLint roadmap section](https://www.sonarsource.com/products/sonarlint/roadmap/).

**Comment by sollidsnake** [comment]
I see, thanks for the clarification. Hopefully it will happen soon now that the new Microsoft's LSP for C# is being released.

**Comment by Horrih** [comment]
I am not well versed in the C# ecosystem, but it looks like VSCode's sonarlint comes with omnisharp support now.
I just submitted [a PR](https://github.com/emacs-lsp/lsp-sonarlint/pull/22) to allow lsp-sonarlint to use the VSCode extension's analyzers, including omnisharp.

However a few additional tweaks may be needed to make omnisharp work. Feel free to try it out.

**Comment by Sasanidas** [comment]
https://github.com/emacs-lsp/lsp-sonarlint/pull/22 merged, so this should work :+1:
